### ISSUE TITLE
Build Out Filtering/Sorting Functionality

### ISSUE THREAD

**Issue by habraham2023** [habraham2023/Abes_Car_Dealership#18]
- [x] Add input for filtering by distance
- [x] If max distance value is given filter out listings with distances larger than given
- [x] Add Drop down menu for order of sorting, to start implement price, distance, and date of creation sorting

**Comment by ycjlin** [comment]
For the filtering algorithm, maybe we can try to make it more complex.
For instance, filtering on multiple dimensions - e.g. things under $10 that have been on the market for < 1 day

**Comment by ycjlin** [comment]
A potential stretch goal idea: adding a button for "Map" on the listing tab to show directions on Google Map.
